spring:
  application:
    name: product-services
  cloud:
    function:
      definition: consumeOrderCreated 
    stream:
      bindings:
        testEvent-out-0:
          destination: test-topic # hangi başlığa bu eventi göndereyim?
          content-type: application/json # hangi tür ile göndereyim?

        consumeOrderCreated-in-0:
          destination: order-created-topic 
          group: product-service-group 
      kafka:
        binder:
          brokers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5433/products
    username: postgres
    password: test12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080