spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/products # İleride cart-db açarsan port/db adını güncellersin reis
    username: postgres
    password: test12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/